### ISSUE TITLE
how to send a dbus command using ipmitool

### ISSUE THREAD

**Issue by liufujun135** [openbmc/ipmitool#3]
hi,
I have a client machine that installed the ipmitool(dbus version) and a palmetto server that flashed the openbmc codes. I can access the interface through ipaddress:3000 on browser. But I can not send dbus command through ipmitool and there is no timeout or any response.

the command is as follow:
ipmitool -I dbus -H bmc_ipaddress -U root -P 0penBmc power status.

So what is the command that dbus support or how to send a command through dbus interface?

**Comment by williamspatrick** [comment]
What you are asking for is not currently possible. The OpenBMC code does not expose an ipmi interface externally, over network or dbus.  For production purposes you should be using the REST interfaces on the standard https port (and not the debug server on port 3000). 

This Ipmitool is only useful if ran directly on the BMC. The purpose of it is as a debug aid for those developing ipmi handlers on the BMC. These handlers are to emulate enough of the host-ipmi stack so that existing firmware/bios code can be ran on top of OpenBMC.

**Comment by liufujun135** [comment]
Got it.
Thanks a lot.
